version: '3.9'

services:

  app:
    build:
      context: ../part_4_and_5/.
      dockerfile: Dockerfile
    networks:
      - app_network

  proxy:
    image: nginx:alpine
    ports:
      - 80:8080
    volumes:
      - ./nginx/proxy.conf:/etc/nginx/nginx.conf
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
